<?xml version="1.0" encoding="UTF-8"?>
<Profile xmlns="http://soap.sforce.com/2006/04/metadata">
    <applicationVisibilities>
        <application>CCA</application>
        <default>false</default>
        <visible>false</visible>
    </applicationVisibilities>
    <applicationVisibilities>
        <application>ForceSolution</application>
        <default>false</default>
        <visible>false</visible>
    </applicationVisibilities>
    <applicationVisibilities>
        <application>RAOC</application>
        <default>false</default>
        <visible>false</visible>
    </applicationVisibilities>
    <classAccesses>
        <apexClass>AnsweringQuestionsCtrl</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>AnsweringQuestionsCtrlTest</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>ApplicationByClassificationController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>ApplicationGoalHelper</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>ApplicationGoalScoreHelper</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>ApplicationResultController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>ApplicationWraper</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>AppsByGoalController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>AssignApplicationsToGoalsController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>AssignGiftCtrl</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>AssigningtheQuestionsController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>CallChecker</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>ChangePasswordController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>ChatterAnswersAuthProviderRegistration</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>ChatterAnswersCreateAccountTest</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>ChatterAnswersEscalationTriggerTest</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>ChatterAnswersRegistration</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>CodeCoverageCheat</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>CodeCoverageCheat2</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>CommunitiesLandingController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>CommunitiesLandingControllerTest</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>CommunitiesLoginController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>CommunitiesLoginControllerTest</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>CommunitiesSelfRegConfirmController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>CommunitiesSelfRegConfirmControllerTest</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>CommunitiesSelfRegController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>CommunitiesSelfRegControllerTest</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>CookieHelperController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>CreatePRController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>ForgotPasswordController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>HomeController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>ManageQuestionsController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>MyProfilePageController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>MyProfilePageControllerTest</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>QuestionDetailsController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>RAOCTest</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>RAOCUtill</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>RegisteredUserController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>RegistrationController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>SignInController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>SiteContactHandler</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>SiteExpertiseController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>SiteHomeController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>SiteLoginController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>SiteRegisterController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestApplicationByClassification</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestApplicationGoalScoreTrigger</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestApplicationResultController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestAppsByGoalController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestAssignApplictionToGoalController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestAssigningtheQuestionsController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestCallChecker</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestChatterAnswersAuthProviderReg</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestCodeCoverage</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestCommunitiesLandingController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestCreatePRController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestFridayWeekEnd</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestManageQuestionsController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestPRHoursAdjust</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestQuestionDetailsController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestSiteContactHandler</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestSiteExpertiseController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestSiteHomeController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestTimeCardEntryController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestTotalTimeCardInfoController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestTwilioCallHandler</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestUpdateCaseOnPRComplete</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TestaffectProjectRequestActuals</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TimeCardEntryController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TotalTimeCardInfoController</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TwilioCallHandler</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>prToHoursAdjust</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Account.AccountNumber</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Account.AccountSource</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Account.AnnualRevenue</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Account.BillingAddress</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Account.Days_Since_Activity__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Account.Description</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Account.Fax</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Account.Google_Maps_Link__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Account.Industry</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Account.Jigsaw</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Account.NumberOfEmployees</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Account.Ownership</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Account.ParentId</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Account.Phone</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Account.Rating</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Account.Region__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Account.Satisfaction_Indicator__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Account.Satisfaction_Level__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Account.ShippingAddress</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Account.Sic</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Account.SicDesc</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Account.Site</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Account.TickerSymbol</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Account.Total_Won_Opportunities__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Account.Type</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Account.Website</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Application__c.Account__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Application__c.Best_Fit_Goal__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Application__c.Best_Goal_For_App_Number_Of_Questions__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Application__c.Business_Owner_of_the_Application__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Application__c.Classification__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Application__c.Completed__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Application__c.Description__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Application__c.Selected__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Application__c.Type__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Asset.AccountId</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Asset.ContactId</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Asset.Description</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Asset.InstallDate</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Asset.IsCompetitorProduct</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Asset.Price</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Asset.Product2Id</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Asset.ProductCode</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Asset.ProductDescription</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Asset.ProductFamily</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Asset.PurchaseDate</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Asset.Quantity</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Asset.SerialNumber</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Asset.Status</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Asset.UsageEndDate</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Account_Goal__c.Account__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Account_Goal__c.CCA2_Goal__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Account_Goal__c.Unique_Id__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Answer__c.Answer_Details__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Answer__c.High_Value__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Answer__c.Low_Value__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Answer__c.PicklistResponse__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Answer__c.Position__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Answer__c.Question__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Application_Goal_Score__c.Answered__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Application_Goal_Score__c.App_Name__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Application_Goal_Score__c.CCA2_Application_Goal__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Application_Goal_Score__c.CCA2_Response__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Application_Goal_Score__c.Question__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Application_Goal_Score__c.Recommended_goal_score_range__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Application_Goal_Score__c.Response__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Application_Goal_Score__c.Score__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Application_Goal__c.AccountID__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Application_Goal__c.Account_Name__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Application_Goal__c.Application_Name__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Application_Goal__c.CCA2_Account_Goal__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Application_Goal__c.CCA2_Application__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Application_Goal__c.Completed__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Application_Goal__c.Exclude__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Application_Goal__c.Goal_Name__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Application_Goal__c.Number_of_Answered_Questions_Formula__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Application_Goal__c.Number_of_Answered_Questions__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Application_Goal__c.Total_Score__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Application_Goal__c.Total_X_Score__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Application_Goal__c.Unique_Id__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Goal_Question__c.CCA2_Goal__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Goal_Question__c.CCA2_Question__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Goal_Question__c.ConcatenatedFields__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Goal_Question__c.Recommended_goal_score_range__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Goal_Question__c.Unique_Id__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Goal_Score__c.Answer__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Goal_Score__c.CCA2_Goals__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Goal_Score__c.Exclude__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Goal_Score__c.Score__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Goal_Score__c.Unique_Id__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Goal__c.Max_Goal_Score__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Question__c.Category__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Question__c.Gate__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Question__c.Question_Describe__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Question__c.Sequence__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Question__c.Type__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Response__c.Account__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Response__c.Answer_Text__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Response__c.Answer__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Response__c.CCA2_Application__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Response__c.CCA2_Question__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Response__c.Gate__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Response__c.Question_Sequence__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Response__c.TEST_ANSWER__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>CCA2_Response__c.Unique_Id__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Campaign.ActualCost</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Campaign.AmountAllOpportunities</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Campaign.AmountWonOpportunities</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Campaign.BudgetedCost</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Campaign.Campaign_ROI__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Campaign.Description</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Campaign.EndDate</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Campaign.ExpectedResponse</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Campaign.ExpectedRevenue</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Campaign.HierarchyActualCost</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Campaign.HierarchyAmountAllOpportunities</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Campaign.HierarchyAmountWonOpportunities</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Campaign.HierarchyBudgetedCost</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Campaign.HierarchyExpectedRevenue</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Campaign.HierarchyNumberOfContacts</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Campaign.HierarchyNumberOfConvertedLeads</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Campaign.HierarchyNumberOfLeads</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Campaign.HierarchyNumberOfOpportunities</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Campaign.HierarchyNumberOfResponses</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Campaign.HierarchyNumberOfWonOpportunities</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Campaign.HierarchyNumberSent</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Campaign.IsActive</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Campaign.NumberOfContacts</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Campaign.NumberOfConvertedLeads</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Campaign.NumberOfLeads</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Campaign.NumberOfOpportunities</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Campaign.NumberOfResponses</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Campaign.NumberOfWonOpportunities</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Campaign.NumberSent</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Campaign.ParentId</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Campaign.StartDate</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Campaign.Status</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Campaign.Type</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.AccountId</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.Actual_Hours__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.AssetId</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.BusinessHoursId</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.ClosedDate</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.ClosedOnCreate</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Case.ContactId</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.Customer_Comments__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Case.Description</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.IsClosedOnCreate</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.IsEscalated</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.IsSelfClosed</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.IsSelfServiceClosed</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.IsVisibleInCss</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.IsVisibleInSelfService</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.Level_of_Effort__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.Origin</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Case.ParentId</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Case.Priority</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.Priority_Flag__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.Project__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.QuestionId</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.Reason</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.Severity__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.SourceId</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Case.Subject</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.SuppliedCompany</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.SuppliedEmail</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.SuppliedName</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.SuppliedPhone</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Case.TFS_Comments__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Case.Type</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contact.AccountId</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Contact.AssistantName</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Contact.AssistantPhone</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contact.Birthdate</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Contact.CanAllowPortalSelfReg</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Contact.Department</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contact.Description</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Contact.DoNotCall</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contact.Email</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Contact.Fax</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Contact.HasOptedOutOfEmail</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Contact.HasOptedOutOfFax</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Contact.HomePhone</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Contact.Hourly_Rate__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contact.Jigsaw</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contact.LeadSource</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contact.MailingAddress</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Contact.MobilePhone</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Contact.Normalize_Phone__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contact.OtherAddress</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Contact.OtherPhone</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contact.Phone</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contact.ReportsToId</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contact.Title</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Contact.Total_Hours_Worked__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>ContentVersion.Creator_Email__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Contract.ActivatedById</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Contract.ActivatedDate</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contract.BillingAddress</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contract.CompanySignedDate</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contract.CompanySignedId</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contract.ContractTerm</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contract.CustomerSignedDate</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contract.CustomerSignedId</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contract.CustomerSignedTitle</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contract.Description</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Contract.EndDate</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Contract.Name</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contract.OwnerExpirationNotice</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contract.ShippingAddress</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contract.SpecialTerms</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Contract.StartDate</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Event.Description</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Event.IsAllDayEvent</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Event.IsVisibleInSelfService</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Event.Location</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Event.Type</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Event.WhatId</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Event.WhoId</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Expertise__c.Details__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Expertise__c.Order__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Expertise__c.Tag__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Gift_Reported__c.Child__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Gift_Reported__c.Gift_Value__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Gift_Reported__c.Gift__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Gift__c.Expected_Delivery__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Gift__c.Gift_Value__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Gift__c.Giver_Reddit_Username__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Gift__c.IP_Address__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Gift__c.Legacy_Id__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Gift__c.Offer_Comment__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Gift__c.Receiver__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Gift__c.Status__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Gift__c.Suspicious__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Idea.Attachment</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Idea.Status</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Lead.Address</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Lead.AnnualRevenue</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Lead.Description</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Lead.Disqual_Reason__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Lead.DoNotCall</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Lead.Email</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Lead.Fax</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Lead.HasOptedOutOfEmail</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Lead.HasOptedOutOfFax</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Lead.Industry</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Lead.Interest__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Lead.Jigsaw</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Lead.LastTransferDate</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Lead.LeadSource</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Lead.MobilePhone</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Lead.NumberOfEmployees</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Lead.Phone</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Lead.Rating</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Lead.SFGA__CorrelationID__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Lead.SFGA__Correlation_Data__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Lead.SFGA__Web_Source__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Lead.Star_Rating__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Lead.Title</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Lead.Website</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Opportunity.AccountId</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Opportunity.Amount</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Opportunity.CampaignId</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Opportunity.ContractId</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Opportunity.Description</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Opportunity.ExpectedRevenue</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Opportunity.IsPrivate</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Opportunity.LeadSource</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Opportunity.NextStep</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Opportunity.Probability</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Opportunity.STZebra__ZebraColor__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Opportunity.STZebra__Zebra_Color__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Opportunity.STZebra__Zebra_Scores__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Opportunity.TotalOpportunityQuantity</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Opportunity.Type</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Opportunity.Winning_Competitor__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>OpportunityLineItem.Description</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>OpportunityLineItem.Discount</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>OpportunityLineItem.ListPrice</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>OpportunityLineItem.ProductCode</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>OpportunityLineItem.ServiceDate</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>OpportunityLineItem.Subtotal</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>OpportunityLineItem.TotalPrice</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Payment__c.Amount__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Payment__c.Date_Paid__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Payment__c.Vendor__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Person__c.Age__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Person__c.Date_Of_Approval__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Person__c.Email__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Person__c.Gift_Received__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Person__c.IP_Address__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Person__c.Leagacy_Id__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Person__c.Notes_to_the_Moderators__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Person__c.Parent_Username__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Person__c.PasswordT__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Person__c.Phone__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Person__c.Receiver__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Person__c.Reddit_Username__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Person__c.Redit_Username_Normal__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Person__c.Registration_Status__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Person__c.Rejection_Reason__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Person__c.Wishlist_URL__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Product2.Description</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Product2.Family</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Product2.ProductCode</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Project_Request__c.Actual_Hours__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Project_Request__c.Case__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Project_Request__c.Completion_Summary__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Project_Request__c.Description__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Project_Request__c.Developer__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Project_Request__c.ProjectName__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Project_Request__c.Project__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Project_Request__c.Status__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Project__c.Account__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Project__c.Customer_Owner__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Project__c.Description__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Project__c.deployed__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPersona.AreWeFollowing</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPersona.Bio</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPersona.Followers</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPersona.Following</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPersona.IsBlacklisted</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPersona.IsFollowingUs</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPersona.Klout</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPersona.ListedCount</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPersona.MediaProvider</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPersona.MediaType</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPersona.NumberOfFriends</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPersona.NumberOfTweets</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPersona.ProfileType</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPersona.R6SourceId</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPersona.RealName</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPersona.SourceApp</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPersona.TopicType</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPersona.UserId</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.AnalyzerScore</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.AssignedTo</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.AttachmentType</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.AttachmentUrl</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.Classification</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.CommentCount</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.Content</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.DeletedById</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.EngagementLevel</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.ExternalPostId</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.HarvestDate</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.InboundLinkCount</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.IsOutbound</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.KeywordGroupName</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.Language</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.LikesAndVotes</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.MediaProvider</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.MediaType</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.MessageType</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.OutboundSocialAccountId</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.ParentId</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.PersonaId</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.PostPriority</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.PostTags</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.PostUrl</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.R6PostId</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.R6SourceId</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.R6TopicId</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.Recipient</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.RecipientType</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.ReplyToId</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.ResponseContextExternalId</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.ReviewedStatus</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.Sentiment</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.Shares</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.SourceTags</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.SpamRating</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.Status</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.StatusMessage</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.ThreadSize</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.TopicProfileName</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.TopicType</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.UniqueCommentors</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.ViewCount</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>SocialPost.WhoId</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Solution.IsPublished</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Solution.IsPublishedInPublicKb</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Solution.SolutionNote</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Suspicious_IP_Address__c.Gift__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Suspicious_IP_Address__c.Reason__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Task.ActivityDate</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Task.Description</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Task.IsVisibleInSelfService</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Task.Type</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Task.WhatId</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Task.WhoId</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Test_Detail_Obj__c.Account__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Time_Card__c.Comments__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Time_Card__c.Day__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Time_Card__c.Developer__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Time_Card__c.Hours__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Time_Card__c.Month_Ending__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Time_Card__c.Project_Request__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Time_Card__c.Week_Ending__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Twilio_Call_History__c.From__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Twilio_Call_History__c.Status__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Twilio_Call_History__c.To__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>User.Normalize_Phone__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>User.Twilio_Number__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <layoutAssignments>
        <layout>Account-Account Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Application__c-Application Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Asset-Asset Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>CCA2_Account_Goal__c-Account Goal Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>CCA2_Answer__c-Answer Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>CCA2_Application_Goal_Score__c-Application Goal Score Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>CCA2_Application_Goal__c-Application Goal Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>CCA2_Goal_Question__c-Goal Question Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>CCA2_Goal_Score__c-Goal Score Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>CCA2_Goal__c-Goal Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>CCA2_Question__c-Question Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>CCA2_Response__c-Response Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Campaign-Campaign Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>CampaignMember-Campaign Member Page Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Case-Case Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Case-Case Layout</layout>
        <recordType>Case.Bug</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Case-Case Layout</layout>
        <recordType>Case.Requirement</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Case-Case Layout</layout>
        <recordType>Case.test</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>CaseClose-Close Case Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Contact-Contact Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>ContentVersion-FlipCard</layout>
        <recordType>ContentVersion.FlipCard</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>ContentVersion-General</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Contract-Contract Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>DuplicateRecordSet-Duplicate Record Set Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Event-Event Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Expertise__c-Expertise Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>FeedItem-Feed Item Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Gift_Reported__c-Gift Reported Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Gift__c-Gift Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Idea-Idea Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Lead-Lead Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Macro-Macro Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Opportunity-Opportunity Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>OpportunityLineItem-Opportunity Product Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Payment__c-Payment Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Person__c-Child</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Person__c-Child</layout>
        <recordType>Person__c.Admin</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Person__c-Child</layout>
        <recordType>Person__c.Child</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Person__c-Child</layout>
        <recordType>Person__c.Receiver</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Pricebook2-Price Book Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>PricebookEntry-Price Book Entry Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Product2-Product Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Project_Request__c-Project Request Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Project__c-Project Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Question-Question Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Reply-Reply Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Solution-Solution Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Suspicious_IP_Address__c-Suspicious IP Address Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Task-Task Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Test_Detail_Obj__c-Test Detail Obj Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Time_Card__c-Time Card Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Twilio_Call_History__c-Twilio Call History Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>User-User Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>UserAlt-User Profile Layout</layout>
    </layoutAssignments>
    <objectPermissions>
        <object>Account</object>
    </objectPermissions>
    <objectPermissions>
        <object>Application__c</object>
    </objectPermissions>
    <objectPermissions>
        <object>Asset</object>
    </objectPermissions>
    <objectPermissions>
        <object>CCA2_Account_Goal__c</object>
    </objectPermissions>
    <objectPermissions>
        <object>CCA2_Answer__c</object>
    </objectPermissions>
    <objectPermissions>
        <object>CCA2_Application_Goal_Score__c</object>
    </objectPermissions>
    <objectPermissions>
        <object>CCA2_Application_Goal__c</object>
    </objectPermissions>
    <objectPermissions>
        <object>CCA2_Goal_Question__c</object>
    </objectPermissions>
    <objectPermissions>
        <object>CCA2_Goal_Score__c</object>
    </objectPermissions>
    <objectPermissions>
        <object>CCA2_Goal__c</object>
    </objectPermissions>
    <objectPermissions>
        <object>CCA2_Question__c</object>
    </objectPermissions>
    <objectPermissions>
        <object>CCA2_Response__c</object>
    </objectPermissions>
    <objectPermissions>
        <object>Campaign</object>
    </objectPermissions>
    <objectPermissions>
        <object>Case</object>
    </objectPermissions>
    <objectPermissions>
        <object>Contact</object>
    </objectPermissions>
    <objectPermissions>
        <allowCreate>true</allowCreate>
        <allowDelete>true</allowDelete>
        <allowEdit>true</allowEdit>
        <allowRead>true</allowRead>
        <object>Contract</object>
    </objectPermissions>
    <objectPermissions>
        <object>DuplicateRecordSet</object>
    </objectPermissions>
    <objectPermissions>
        <object>Expertise__c</object>
    </objectPermissions>
    <objectPermissions>
        <object>Gift_Reported__c</object>
    </objectPermissions>
    <objectPermissions>
        <object>Gift__c</object>
    </objectPermissions>
    <objectPermissions>
        <allowRead>true</allowRead>
        <object>Idea</object>
    </objectPermissions>
    <objectPermissions>
        <object>Lead</object>
    </objectPermissions>
    <objectPermissions>
        <object>Macro</object>
    </objectPermissions>
    <objectPermissions>
        <object>Opportunity</object>
    </objectPermissions>
    <objectPermissions>
        <object>Payment__c</object>
    </objectPermissions>
    <objectPermissions>
        <object>Person__c</object>
    </objectPermissions>
    <objectPermissions>
        <allowRead>true</allowRead>
        <object>Pricebook2</object>
    </objectPermissions>
    <objectPermissions>
        <allowRead>true</allowRead>
        <object>Product2</object>
    </objectPermissions>
    <objectPermissions>
        <object>Project_Request__c</object>
    </objectPermissions>
    <objectPermissions>
        <object>Project__c</object>
    </objectPermissions>
    <objectPermissions>
        <object>SocialPost</object>
    </objectPermissions>
    <objectPermissions>
        <object>Solution</object>
    </objectPermissions>
    <objectPermissions>
        <object>StreamingChannel</object>
    </objectPermissions>
    <objectPermissions>
        <object>Suspicious_IP_Address__c</object>
    </objectPermissions>
    <objectPermissions>
        <object>Test_Detail_Obj__c</object>
    </objectPermissions>
    <objectPermissions>
        <object>Time_Card__c</object>
    </objectPermissions>
    <objectPermissions>
        <object>Twilio_Call_History__c</object>
    </objectPermissions>
    <pageAccesses>
        <apexPage>AnsweringQuestions</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>AnswersHome</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>ApplicationByClassification</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>ApplicationResult</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>AppsByGoal</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>AssignApplicationsToGoals</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>AssigningtheQuestions</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>BandwidthExceeded</apexPage>
        <enabled>true</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>CallChecker</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>CaseStudy</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>ChangePassword</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>ChatterAnswersAgentView</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>ChatterAnswersChangePassword</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>ChatterAnswersForgotPassword</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>ChatterAnswersForgotPasswordConfirm</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>ChatterAnswersHelp</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>ChatterAnswersLogin</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>ChatterAnswersRegistration</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>CommunitiesLanding</apexPage>
        <enabled>true</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>CommunitiesLogin</apexPage>
        <enabled>true</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>CommunitiesSelfReg</apexPage>
        <enabled>true</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>CommunitiesSelfRegConfirm</apexPage>
        <enabled>true</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>CommunitiesTemplate</apexPage>
        <enabled>true</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>ContactUs</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>CreatePR</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>Create_Profile</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>DemoTest</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>Exception</apexPage>
        <enabled>true</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>FileNotFound</apexPage>
        <enabled>true</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>ForgotPassword</apexPage>
        <enabled>true</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>ForgotPasswordConfirm</apexPage>
        <enabled>true</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>Gift_Given</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>Gifts_Given</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>Home</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>Homepage</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>IdeasHome</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>InMaintenance</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>InfoEdit</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>LoginPage</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>ManageQuestions</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>MyProfilePage</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>OurExpertise</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>Our_Expertise</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>PlayWithDemo</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>QuestionDetails</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>RegisteredUser</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>RelevantAccountNewsFromGoogleNews</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>ResendPassword</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>SiteLogin</apexPage>
        <enabled>true</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>SiteRegister</apexPage>
        <enabled>true</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>SiteRegisterConfirm</apexPage>
        <enabled>true</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>SiteTemplate</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>StdExceptionTemplate</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>Timecard_Entry</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>Total_Time_Cards_And_Payments</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>TwilioCallHandler</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>Unauthorized</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>UnderConstruction</apexPage>
        <enabled>true</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>WhatWeDo</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>raoc_exception</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>receivedgift</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <pageAccesses>
        <apexPage>receiververification</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Case.Bug</recordType>
        <visible>false</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Case.Requirement</recordType>
        <visible>false</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Case.test</recordType>
        <visible>false</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>ContentVersion.FlipCard</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Idea.InternalIdeasIdeaRecordType</recordType>
        <visible>false</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Person__c.Admin</recordType>
        <visible>false</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Person__c.Child</recordType>
        <visible>false</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Person__c.Receiver</recordType>
        <visible>false</visible>
    </recordTypeVisibilities>
    <tabVisibilities>
        <tab>standard-DuplicateRecordSet</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>standard-Idea</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
</Profile>
